### ISSUE TITLE
[BUG] `ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/{vanilla,foss,gapps}.json, error: 404`

### ISSUE THREAD

**Issue by Benjamin-Loison** [Benjamin-Loison/waydroid#26]
### Describe the bug

On Linux Mint Framework VirtualBox `Linux Mint (trust)` virtual machine. No matter that I performed `sudo sysctl net.ipv6.conf.all.disable_ipv6=1`.

```bash
sudo waydroid init -f -s foss
```
<details>
<summary>Output:</summary>

```
[02:02:03] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/foss.json, error: 404
[02:02:03] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
</details>

```bash
sudo waydroid init -f -s vanilla
```
<details>
<summary>Output:</summary>

```
[02:02:07] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/vanilla.json, error: 404
[02:02:07] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
</details>

```bash
sudo waydroid init -f -s gapps
```
<details>
<summary>Output:</summary>

```
[02:02:12] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/gapps.json, error: 404
[02:02:12] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
</details>

```bash
waydroid log
```
<details>
<summary>Output:</summary>

```
(005554) [02:02:03] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/foss.json, error: 404
(005554) [02:02:03] See also: <https://github.com/waydroid>
(005554) [02:02:03] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/foss.json, error: 404

(005557) [02:02:07] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/vanilla.json, error: 404
(005557) [02:02:07] See also: <https://github.com/waydroid>
(005557) [02:02:07] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/vanilla.json, error: 404

(005584) [02:02:12] ERROR: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/gapps.json, error: 404
(005584) [02:02:12] See also: <https://github.com/waydroid>
(005584) [02:02:12] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: https://ota.waydro.id/system/lineage/waydroid_x86_64/gapps.json, error: 404
```
</details>

### Waydroid version

Not read.

### Device

Linux Desktop

### Operating System

Not read.

### Kernel version

Not read.

### Desktop Environment

Not read.

### GPU

Not read.

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Benjamin-Loison** [comment]
Let us try without `-f` on a quite fresh environment:

**Comment by Benjamin-Loison** [comment]
I forgot that it is case sensitive.
